### ISSUE TITLE
Testdaten hinzufügen

### ISSUE THREAD

**Issue by lordpomeroy** [imis-Infektionsfall-uebermittellung/1_011_a_infektionsfall_uebermittellung#1]
In der Datenbank sollte ein Satz an Dummydaten verfügbar sein, um die Frontendteile und auch die Schnittstellen zu entwickeln.

**Comment by lordpomeroy** [comment]
https://docs.google.com/spreadsheets/d/e/2PACX-1vQU0SIALScXx8VXDX7yKNKWWPKE1YjFlWc6VTEVSN45CklWWf-uWmprQIyLtoPDA18tX9cFDr-aQ9S6/pubhtml
wäre ein guter Startpunkt

**Comment by JonasCir** [comment]
Done
