### ISSUE TITLE
[client]  Should client/package-lock.json be in .gitngore? 

### ISSUE THREAD

**Issue by JonasCir** [imis-Infektionsfall-uebermittellung/1_011_a_infektionsfall_uebermittellung#18]
Otherwise add to .gitignore and run git rm --cached client/package-lock.json :)

**Comment by JonasCir** [comment]
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

**Comment by marco74** [comment]
Nein, auf keinen Fall, package-lock.json sollte eigenlich committed werden. Dort steht drin, welche Version genau du jetzt installiert hat. Wenn die nicht am Server landet, dann kann es sein, dass dort einen geringfügig andere Version installiert und Dinge dann anders funktionieren als es bei dir der Fall ist.

**Comment by MichaelSp** [comment]
`client/package-lock.json` muss nicht comitted werden: Es wird yarn mit `client/yarn.lock` verwendet.
