### ISSUE TITLE
Docker File for Server backend

### ISSUE THREAD

**Issue by marco74** [imis-Infektionsfall-uebermittellung/1_011_a_infektionsfall_uebermittellung#2]
Könnt ihr das Backend auch bitte dockerizen und im docker-compoze als Service eintragen? So muss man als reiner FE-Entwickler nicht den ganzen Java-Stack installieren.

**Comment by Smokrow** [comment]
Ich gucke mal was da so geht :)

**Comment by Smokrow** [comment]
Soweit ich das mit hängt der Vue JS server im Backend. Dementsprechend brauchen wir nur ein einzelnes Dockerfile

**Comment by marco74** [comment]
Java sollte in Docker hinein, sonst muss jeder FE-Entwickler sich den Blödsinn nativ auf den Rechner installieren.

**Comment by marco74** [comment]
Wenn wir dafür dann das Dockerfile haben können wir es nämlich auch gleich in docker-compose hinterlegen, dann wird auch die Installationsanleitung einfacher.

**Comment by Smokrow** [comment]
On It

**Comment by Smokrow** [comment]
Erste Version liegt unter moritz/docker einfach mal ausprobieren. Ich bin leider jetzt erstmal 3 Std weg. Viel Erfolg

**Comment by luxn** [comment]
Habe es soweit aufgegriffen, getestet und in dev gemerged.
