### ISSUE TITLE
Docker-Container web startet nicht richtig

### ISSUE THREAD

**Issue by marco74** [imis-Infektionsfall-uebermittellung/1_011_a_infektionsfall_uebermittellung#26]
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

Reproduktion:
```
$ docker-compose build
$ docker-compose up
```

**Comment by MichaelSp** [comment]
ist das noch gültig?

**Comment by marco74** [comment]
Aktuell kann das nicht mehr gültig sein. Im docker-compose wurde der web-container auskommentiert. Wenn er nicht gestartet wird, kann er auch nicht vorzeitig beendet werden.
