### ISSUE TITLE
Links bei deployment funktionieren nicht

### ISSUE THREAD

**Issue by Maccodonaldo** [imis-Infektionsfall-uebermittellung/1_011_a_infektionsfall_uebermittellung#43]
Wenn man auf die http://imis-prototyp.de Seite geht funktioniert die Seite. geht man aber direkt auf http://imis-prototyp.de/patient-data wird man auf die NGINX 404 Seite weitergeleitet

**Comment by MichaelSp** [comment]
Ja sehr merkwürdig. Habe leider keine Ahnung wie ich das fixen könnte.

**Comment by MichaelSp** [comment]
done
