### ISSUE TITLE
Patientenentität definieren und umsetzen

### ISSUE THREAD

**Issue by inc-ali** [imis-Infektionsfall-uebermittellung/1_011_a_infektionsfall_uebermittellung#5]
Aus Google Doc:
ID
Name
Vorname
PLZ
Wohnort
Straße
Hausnummer
Geschlecht
Geb. Datum
Telefon
Email
Anlagedatum

**Comment by Seal33** [comment]
Es muss sichergestellt sein, dass der selbe Patient nicht zwei mal gemeldet werden kann

**Comment by inc-ali** [comment]
> Es muss sichergestellt sein, dass der selbe Patient nicht zwei mal gemeldet werden kann

Wie wird die ID generiert, um das sicherzustellen?

**Comment by kuhlmannmarkus** [comment]
Wir könnten Hash(Name+Vorname+PLZ+Straße+Hausnummer+Geb. Datum) wählen

**Comment by inc-ali** [comment]
see #9
